apiVersion: v1
kind: Service
metadata:
  name: {{ include "canvas-handler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "canvas-handler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $val := .Values.service.ports }}
    - port: {{ $val }}
      targetPort: {{ $key }}
      protocol: TCP
      name: {{ $key }}
    {{- end}}
  selector:
    {{- include "canvas-handler.selectorLabels" . | nindent 4 }}
